### ISSUE TITLE
Edit the contact information in profile

### ISSUE THREAD

**Issue by KaleburGit** [CMPUT301W21T36/PhenoCount#16]
US 04.02.01
As an owner or experimenter, I want to edit the contact information in my profile.

Rationale:
In the event that your information changes, you are able to quickly update your profile without losing everything by making a new account

Story points: 7

Risk level: low

**Comment by Charffyyy** [comment]
There is no particular piece of information that is required for the contact info. It could be an email address and/or phone number and whatever else you want, essentially, something that allows one user to reach another in case there is need for discussion.
