### ISSUE TITLE
Specify a keyword, and search for all experiments that are available

### ISSUE THREAD

**Issue by KaleburGit** [CMPUT301W21T36/PhenoCount#18]
US 05.01.01
As an experimenter, I want to specify a keyword, and search for all experiments that are available.

Rationale:
Allow for ease of access to a specific experiment
Allow for experimenters to compare results between experiments

Story points: 10

Risk level: medium

**Comment by Charffyyy** [comment]
Is it sufficient that the keyword search be associated with experiment titles/descriptions? Or should a keyword have something to do with the type of an experiment?

It should include all searchable text fields including username
