### ISSUE TITLE
Add Geo-location to experimental trials 

### ISSUE THREAD

**Issue by KaleburGit** [CMPUT301W21T36/PhenoCount#21]
US 06.02.01
As an experimenter, I want to add Geo-location to experimental trials that need it.

Rationale:
So you know where the experiment took place
Can add related results

Story points: 12

Risk level: medium

**Comment by Charffyyy** [comment]
Geo-location is per trial. Hence, none/some/all of the trials in an experiment may have geo-location data.

**Comment by Charffyyy** [comment]
Some trials will be associated with geolocation. Such as counting things, where were they counted. The geolocation is bound to a trial.

Geolocation will be a latitude and longitude on earth. Generally given to you by the GPS or location services.
For a counting geolocation will give you a map of count points where by say a car was spotted in Edmonton.

**Comment by Charffyyy** [comment]
both owner and experimenters who participate in a public geolocated experiment get to see a map of the response.

**Comment by Charffyyy** [comment]
> When an experiment has geolocation for trials enforced we are making the assumption that all trials must have a geolocation entry

Yes.

> When it is not enforced we assume that geolocations can be added and will be collected and shown for that trial, and are not restricted to being entered.

Right. That's fine.

**Comment by Charffyyy** [comment]
The owner chooses if the experiment is geolocation enabled.

Experimenters who add trials to an experiment should be warned that geolocation is being recorded and submitted.

**Comment by Charffyyy** [comment]
> For geo-location trials, are the experimenters allowed to adjust where their geolocation is? i.e. do we take their location automatically and have that as un-editable, or are they allowed to move it around/manually specify where the geolocation is?

Yes. It is edittable.
