### ISSUE TITLE
See a map of geo-locations of a geo-location enabled experiment

### ISSUE THREAD

**Issue by KaleburGit** [CMPUT301W21T36/PhenoCount#23]
US 06.04.01
As an experimenter, I want to see a map of geo-locations of a geo-location enabled experiment.

Rationale:
Show you location of participants
Get an idea of where the experiment is grabbing its sample population from

Story points: 16

Risk level: high

**Comment by Charffyyy** [comment]
Experiments don't have a clear geo-location, only trials. Plot a trial's geolocation.
